# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
target 'SKDebugToolDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SKNetworkRequest', '~> 0.0.7'
  # Pods for SKDebugToolDemo
pod 'YYModel', '~> 1.0.3'
pod 'Masonry', '~> 1.1.0'
pod 'SKDebugTool', :path => '../'
end
